import {Button} from "@/components/ui/button";
import {useToast} from "@/components/ui/use-toast";

interface CaptchaTokenProps {
  token: string;
}

export default function CaptchaToken({token}: CaptchaTokenProps) {
  const {toast} = useToast();

  function handleCopy() {
    navigator.clipboard.writeText(token);
    toast({
      variant: "destructive",
      title: "Token copied to clipboard",
      description: "You can now paste the token where you need it",
    });
  }

  return (
    <div className="flex w-full flex-col items-start justify-center gap-2 overflow-hidden">
      <h6 className="text-sm font-bold">Token provided</h6>
      <div className="flex w-full flex-col items-center justify-end gap-2 overflow-hidden">
        <Button className="w-full" type="button" onClick={handleCopy}>
          Copy
        </Button>
        <p className="w-full text-sm">
          The token below is the one generated by the google recaptcha v3 service.
        </p>
        <code className="flex w-full items-center justify-start gap-4 overflow-hidden hyphens-auto text-xs">
          {token}
        </code>
      </div>
    </div>
  );
}

export {CaptchaToken};
