import type {Metadata} from "next";

import Link from "next/link";

import CaptchaProvider from "@/contexts/captcha/provider";
import "./globals.css";
import {Toaster} from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Captcha",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className="container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] bg-background px-4 font-sans antialiased"
      >
        <header className="text-xl font-bold leading-[4rem]">
          <Link href="/">Captcha</Link>
        </header>
        <CaptchaProvider>
          <main className="py-8">{children}</main>
          <Toaster />
        </CaptchaProvider>
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} Captcha
        </footer>
      </body>
    </html>
  );
}
